CREATE TABLESPACE IA_DAT01 
	 DATAFILE SIZE 2097152000 AUTOEXTEND ON NEXT 128000 MAXSIZE UNLIMITED
	 BLOCKSIZE 8192 
	 LOGGING 
	 ONLINE 
	 EXTENT MANAGEMENT LOCAL AUTOALLOCATE 
	 SEGMENT SPACE MANAGEMENT MANUAL 
;
CREATE TABLESPACE IA_DAT02 
	 DATAFILE SIZE 51183616 AUTOEXTEND ON NEXT 1 MAXSIZE UNLIMITED
	 BLOCKSIZE 8192 
	 LOGGING 
	 ONLINE 
	 EXTENT MANAGEMENT LOCAL AUTOALLOCATE 
	 SEGMENT SPACE MANAGEMENT MANUAL 
;
CREATE TABLESPACE IA_DAT03 
	 DATAFILE SIZE 42205184 AUTOEXTEND ON NEXT 1 MAXSIZE UNLIMITED
	 BLOCKSIZE 8192 
	 LOGGING 
	 ONLINE 
	 EXTENT MANAGEMENT LOCAL AUTOALLOCATE 
	 SEGMENT SPACE MANAGEMENT MANUAL 
;
CREATE TABLESPACE IA_DAT04 
	 DATAFILE SIZE 5242880 AUTOEXTEND ON NEXT 1 MAXSIZE UNLIMITED 
	 BLOCKSIZE 8192 
	 LOGGING 
	 ONLINE 
	 EXTENT MANAGEMENT LOCAL AUTOALLOCATE 
	 SEGMENT SPACE MANAGEMENT MANUAL 
;
CREATE TABLESPACE IA_DAT05 
	 DATAFILE SIZE 5242880 AUTOEXTEND ON NEXT 1 MAXSIZE UNLIMITED 
	 BLOCKSIZE 8192 
	 LOGGING 
	 ONLINE 
	 EXTENT MANAGEMENT LOCAL AUTOALLOCATE 
	 SEGMENT SPACE MANAGEMENT MANUAL 
;
CREATE TABLESPACE IA_DAT06 
	 DATAFILE SIZE 5242880 AUTOEXTEND ON NEXT 1 MAXSIZE UNLIMITED 
	 BLOCKSIZE 8192 
	 LOGGING 
	 ONLINE 
	 EXTENT MANAGEMENT LOCAL AUTOALLOCATE 
	 SEGMENT SPACE MANAGEMENT MANUAL 
;
CREATE TABLESPACE IA_DAT07 
	 DATAFILE SIZE 5242880 AUTOEXTEND ON NEXT 1 MAXSIZE UNLIMITED 
	 BLOCKSIZE 8192 
	 LOGGING 
	 ONLINE 
	 EXTENT MANAGEMENT LOCAL AUTOALLOCATE 
	 SEGMENT SPACE MANAGEMENT MANUAL 
;
CREATE TABLESPACE IA_DAT08 
	 DATAFILE SIZE 5242880 AUTOEXTEND ON NEXT 1 MAXSIZE UNLIMITED
	 BLOCKSIZE 8192 
	 LOGGING 
	 ONLINE 
	 EXTENT MANAGEMENT LOCAL AUTOALLOCATE 
	 SEGMENT SPACE MANAGEMENT MANUAL 
;
CREATE TABLESPACE IA_ETL_DAT01 
	 DATAFILE SIZE 2097152000 AUTOEXTEND ON NEXT 128000 MAXSIZE UNLIMITED
	 BLOCKSIZE 8192 
	 LOGGING 
	 ONLINE 
	 EXTENT MANAGEMENT LOCAL AUTOALLOCATE 
	 SEGMENT SPACE MANAGEMENT MANUAL 
;
CREATE TABLESPACE IA_ETL_DAT02 
	 DATAFILE SIZE 150601728 AUTOEXTEND ON NEXT 1 MAXSIZE UNLIMITED 
	 BLOCKSIZE 8192 
	 LOGGING 
	 ONLINE 
	 EXTENT MANAGEMENT LOCAL AUTOALLOCATE 
	 SEGMENT SPACE MANAGEMENT MANUAL 
;
CREATE TABLESPACE IA_ETL_DAT03 
	 DATAFILE SIZE 70975488 AUTOEXTEND ON NEXT 1 MAXSIZE UNLIMITED 
	 BLOCKSIZE 8192 
	 LOGGING 
	 ONLINE 
	 EXTENT MANAGEMENT LOCAL AUTOALLOCATE 
	 SEGMENT SPACE MANAGEMENT MANUAL 
;
CREATE TABLESPACE IA_ETL_IDX01 
	 DATAFILE SIZE 5505024 AUTOEXTEND ON NEXT 1 MAXSIZE UNLIMITED
	 BLOCKSIZE 8192 
	 LOGGING 
	 ONLINE 
	 EXTENT MANAGEMENT LOCAL AUTOALLOCATE 
	 SEGMENT SPACE MANAGEMENT MANUAL 
;
CREATE TABLESPACE IA_ETL_IDX02 
	 DATAFILE SIZE 23986176 AUTOEXTEND ON NEXT 1 MAXSIZE UNLIMITED
	 BLOCKSIZE 8192 
	 LOGGING 
	 ONLINE 
	 EXTENT MANAGEMENT LOCAL AUTOALLOCATE 
	 SEGMENT SPACE MANAGEMENT MANUAL 
;
CREATE TABLESPACE IA_ETL_IDX03 
	 DATAFILE SIZE 29884416 AUTOEXTEND ON NEXT 1 MAXSIZE UNLIMITED
	 BLOCKSIZE 8192 
	 LOGGING 
	 ONLINE 
	 EXTENT MANAGEMENT LOCAL AUTOALLOCATE 
	 SEGMENT SPACE MANAGEMENT MANUAL 
;
CREATE TABLESPACE IA_IDX01 
	 DATAFILE SIZE 28508160 AUTOEXTEND ON NEXT 1 MAXSIZE UNLIMITED 
	 BLOCKSIZE 8192 
	 LOGGING 
	 ONLINE 
	 EXTENT MANAGEMENT LOCAL AUTOALLOCATE 
	 SEGMENT SPACE MANAGEMENT MANUAL 
;
CREATE TABLESPACE IA_IDX02 
	 DATAFILE SIZE 154140672 AUTOEXTEND ON NEXT 1 MAXSIZE UNLIMITED
	 BLOCKSIZE 8192 
	 LOGGING 
	 ONLINE 
	 EXTENT MANAGEMENT LOCAL AUTOALLOCATE 
	 SEGMENT SPACE MANAGEMENT MANUAL 
;
CREATE TABLESPACE IA_IDX03 
	 DATAFILE SIZE 31195136 AUTOEXTEND ON NEXT 1 MAXSIZE UNLIMITED 
	 BLOCKSIZE 8192 
	 LOGGING 
	 ONLINE 
	 EXTENT MANAGEMENT LOCAL AUTOALLOCATE 
	 SEGMENT SPACE MANAGEMENT MANUAL 
;
CREATE TABLESPACE IA_IDX04 
	 DATAFILE SIZE 5242880 AUTOEXTEND ON NEXT 1 MAXSIZE UNLIMITED
	 BLOCKSIZE 8192 
	 LOGGING 
	 ONLINE 
	 EXTENT MANAGEMENT LOCAL AUTOALLOCATE 
	 SEGMENT SPACE MANAGEMENT MANUAL 
;
CREATE TABLESPACE IA_IDX05 
	 DATAFILE SIZE 5242880 AUTOEXTEND ON NEXT 1 MAXSIZE UNLIMITED
	 BLOCKSIZE 8192 
	 LOGGING 
	 ONLINE 
	 EXTENT MANAGEMENT LOCAL AUTOALLOCATE 
	 SEGMENT SPACE MANAGEMENT MANUAL 
;
CREATE TABLESPACE IA_IDX06 
	 DATAFILE SIZE 5242880 AUTOEXTEND ON NEXT 1 MAXSIZE UNLIMITED
	 BLOCKSIZE 8192 
	 LOGGING 
	 ONLINE 
	 EXTENT MANAGEMENT LOCAL AUTOALLOCATE 
	 SEGMENT SPACE MANAGEMENT MANUAL 
;
CREATE TABLESPACE IA_IDX07 
	 DATAFILE SIZE 5242880 AUTOEXTEND ON NEXT 1 MAXSIZE UNLIMITED
	 BLOCKSIZE 8192 
	 LOGGING 
	 ONLINE 
	 EXTENT MANAGEMENT LOCAL AUTOALLOCATE 
	 SEGMENT SPACE MANAGEMENT MANUAL 
;
CREATE TABLESPACE IA_IDX08 
	 DATAFILE SIZE 5242880 AUTOEXTEND ON NEXT 1 MAXSIZE UNLIMITED
	 BLOCKSIZE 8192 
	 LOGGING 
	 ONLINE 
	 EXTENT MANAGEMENT LOCAL AUTOALLOCATE 
	 SEGMENT SPACE MANAGEMENT MANUAL 
;

CREATE TABLESPACE "IA_ETL_DAT05" 
    LOGGING 
    DATAFILE SIZE 800M
    AUTOEXTEND 
    ON NEXT  8K MAXSIZE  1200M EXTENT MANAGEMENT LOCAL SEGMENT 
    SPACE MANAGEMENT  MANUAL; 

CREATE TABLESPACE "IA_ETL_DAT06" 
    LOGGING 
    DATAFILE SIZE 800M
    AUTOEXTEND 
    ON NEXT  8K MAXSIZE  1200M EXTENT MANAGEMENT LOCAL SEGMENT 
    SPACE MANAGEMENT  MANUAL; 

CREATE TABLESPACE "IA_ETL_DAT07" 
    LOGGING 
    DATAFILE SIZE 800M
    AUTOEXTEND 
    ON NEXT  8K MAXSIZE  1200M EXTENT MANAGEMENT LOCAL SEGMENT 
    SPACE MANAGEMENT  MANUAL; 

CREATE TABLESPACE "IA_ETL_DAT08" 
    LOGGING 
    DATAFILE SIZE 800M
    AUTOEXTEND 
    ON NEXT  8K MAXSIZE  1200M EXTENT MANAGEMENT LOCAL SEGMENT 
    SPACE MANAGEMENT  MANUAL; 

CREATE TABLESPACE "IA_ETL_IDX08" 
    LOGGING 
    DATAFILE SIZE 600M
    AUTOEXTEND 
    ON NEXT  8K MAXSIZE  1200M EXTENT MANAGEMENT LOCAL SEGMENT 
    SPACE MANAGEMENT  MANUAL; 

CREATE TABLESPACE "IA_ETL_IDX05" 
    LOGGING 
    DATAFILE SIZE 600M
    AUTOEXTEND 
    ON NEXT  8K MAXSIZE  1200M EXTENT MANAGEMENT LOCAL SEGMENT 
    SPACE MANAGEMENT  MANUAL; 

CREATE TABLESPACE "IA_ETL_IDX06" 
    LOGGING 
    DATAFILE SIZE 600M
    AUTOEXTEND 
    ON NEXT  8K MAXSIZE  1200M EXTENT MANAGEMENT LOCAL SEGMENT 
    SPACE MANAGEMENT  MANUAL; 

CREATE TABLESPACE "IA_ETL_IDX07" 
    LOGGING 
    DATAFILE SIZE 600M
    AUTOEXTEND 
    ON NEXT  8K MAXSIZE  1200M EXTENT MANAGEMENT LOCAL SEGMENT 
    SPACE MANAGEMENT  MANUAL; 

--IA_EXT schema	
CREATE TABLESPACE "IA_EXT_DAT01" 
	 DATAFILE SIZE 2097152000 AUTOEXTEND ON NEXT 128000 MAXSIZE UNLIMITED
	 BLOCKSIZE 8192 
	 LOGGING 
	 ONLINE 
	 EXTENT MANAGEMENT LOCAL AUTOALLOCATE 
	 SEGMENT SPACE MANAGEMENT MANUAL;

CREATE TABLESPACE "IA_EXT_IDX01"
	 DATAFILE SIZE 28508160 AUTOEXTEND ON NEXT 1 MAXSIZE UNLIMITED
	 BLOCKSIZE 8192 
	 LOGGING 
	 ONLINE 
	 EXTENT MANAGEMENT LOCAL AUTOALLOCATE 
	 SEGMENT SPACE MANAGEMENT MANUAL;
	 
CREATE TABLESPACE WFCRPT_UNKNOWN_DAT01 
	 DATAFILE SIZE 2097152000 AUTOEXTEND ON NEXT 128000 MAXSIZE UNLIMITED 
	 BLOCKSIZE 8192 
	 LOGGING 
	 ONLINE 
	 EXTENT MANAGEMENT LOCAL AUTOALLOCATE 
	 SEGMENT SPACE MANAGEMENT MANUAL ;


